# Generated by Django 4.1.7 on 2023-08-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_set',
            field=models.BooleanField(default=False),
        ),
    ]
